name: 'Cypress Tests'

on:
  workflow_dispatch:

jobs:
  cypress-api:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'

      - name: Configurar cache do Cypress
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Limpar cache do npm
        run: npm cache clean --force

      - name: Instalar dependências
        run: npm install

      - name: Conceder permissão de execução ao Cypress
        run: chmod +x ./node_modules/.bin/cypress

      - name: Instalar binário do Cypress
        run: npx cypress install

      - name: Verificar dependências instaladas
        run: npm list cypress

      - name: Gerar arquivo data.json a partir do secret
        run: |
          echo '${{ secrets.DATA_JSON }}' > cypress/fixtures/data.json

      - name: Executar testes
        run: npx cypress run

      - name: Conceder permissão de execução ao mochawesome-merge e marge
        run: |
          chmod +x ./node_modules/.bin/mochawesome-merge
          chmod +x ./node_modules/.bin/marge

      - name: Gerar relatório
        run: npx mochawesome-merge cypress/reports/*.json > cypress/reports/report.json && npx marge cypress/reports/report.json

      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cypress-report
          path: cypress/reports/
