name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install

      - name: Gerar arquivo data.json a partir do secret
        run: |
          echo '${{ secrets.DATA_JSON }}' > cypress/fixtures/data.json

      - name: Executar testes
        run: npm test

      - name: Gerar relatório
        run: npm run report

      - name: Upload do relatório
        uses: actions/upload-artifact@v3
        if: ${{ !cancelled() }}
        with:
          name: cypress-report
          path: cypress/reports/
